### ISSUE TITLE
Bugs when see detail customer

### ISSUE THREAD

**Issue by PhongzHo** [RSC-Labs/medusa-affiliate-discount#9]
<img width="1757" alt="Screenshot 2024-08-12 at 23 43 22" src="https://github.com/user-attachments/assets/40d3320c-78e1-4785-b51a-33071a804818">

**Comment by radoslaw-sz** [comment]
hi @PhongzHo  - do you have an access to the logs from the backend? Any error is visible?

Did you run db migrations? Just asking to be sure :)

**Comment by PhongzHo** [comment]
yes i was see log from backend and it didn't have any error
I didn't run db migrations before that. thanks for reply so fast 👍

**Comment by radoslaw-sz** [comment]
thanks for the answer, let me know if it works so I could close the issue :)

**Comment by PhongzHo** [comment]
Did u test it works ?

**Comment by radoslaw-sz** [comment]
Yes, I am an author so I tested it before release :)
I asked you to test it if it works on your side to just close this issue :)
